### ISSUE TITLE
Aether is not an eclipse project anymore

### ISSUE THREAD

**Issue by khmarbaise** [luiinge/maven-fetcher#10]
The Eclipse Aether is not an Eclipse project anymore for a longer time..

https://projects.eclipse.org/projects/technology.aether/reviews/termination-review

It has been migrated to https://maven.apache.org/resolver/

**Comment by luiinge** [comment]
Thanks for your comment!
I was aware of that situation, but I had been using the Eclipse version for a while in personal projects without issues, so I though I would be a good starting point. However, it's true that for a public library I should use the up-to-date version.

Version `1.1.0` fixes the issue using `Apache Maven Artifact Resolver` instead of `Eclipse Aether`.
